notifications:
    email: false
language: python
python:
  - "2.7"
before_install:
  - pip install git+git://github.com/biviosoftware/pybivio
install:
  - python setup.py -q install
script:
  - python setup.py test
